name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set Node.js version

      - name: Install Dependencies
        run: |
          npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the build job

    # Only run this job on pushes to the main branch
    if: github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host key to known hosts
        run: echo "${{ secrets.EC2_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          echo "Deploying to AWS EC2"
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'

            # Starting directory
            cd /home/ubuntu

            # Check if the application directory exists, clone if it doesn't
            if [ ! -d "/home/ubuntu/WanderLust" ]; then
                git clone https://github.com/SandyN12058/WanderLust.git
            fi
            
            # Navigate to the application directory
            cd /home/ubuntu/WanderLust

            # Fetch the latest code from the github repository
            git pull origin main

            # Install dependencies
            npm install

            # Restart the app using pm2
            pm2 restart my-app || pm2 start app.js --name my-app

          EOF
